version: "3.9"

services:
  web:
    build: .
    container_name: go-web-app
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - ./data:/app/data

#  sqlite-web:
#    image: coleifer/sqlite-web
#    restart: always
#    ports:
#      - 8081:8080
#    volumes:
#      - ./data:/data
#    command: /data/api.db  # pass the actual DB file, not folder